global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "post-service"
    static_configs:
      - targets: ["post-service:8084"]  # Метрики PostService

  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"]  # Redis Exporter

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]  # RabbitMQ Exporter
      